Add logging
THM-Health/PILOS pull request #113
Opened 2021-02-24 07:59 UTC by SamuelWei

# Fixes #112 

## Type (Highlight the corresponding type)
- Bugfix
- **Feature**
- Documentation
- Refactoring (e.g. Style updates, Test implementation, etc.)
- Other (please describe):

## Checklist
- [x] Code updated to current masters head
- [ ] Passes CI checks
- [x] Is a part of an issue
- [ ] Tests added for the bugfix or newly implemented feature, describe below why if not
- [ ] Changelog is updated
- [ ] Documentation of code and features exists

## Changes

- 
- 
- 
- 

## Other information

2021-02-25 17:34 UTC, dennis95stumm commented
Why you aren't use the application settings instead of configs?

2021-02-25 17:34 UTC, dennis95stumm requested changes
See above!

2021-02-26 11:32 UTC, SamuelWei commented
> Why you aren't use the application settings instead of configs?

I don't think this is something that would need to be changed on a regular basis. It is more a debug tool, like APP_DEBUG and settings like email, database, caching. If we implement #78 we could talk about the pro&cons.

2021-03-01 20:27 UTC, dennis95stumm approved these changes

2021-03-02 07:54 UTC, merged