Refactor room type settings UI
THM-Health/PILOS pull request #1156
Opened 2024-06-17 16:42 UTC by SamuelWei

# Fixes #1101

## Type (Highlight the corresponding type)
- Bugfix
- Feature
- Documentation
- **Refactoring (e.g. Style updates, Test implementation, etc.)**
- Other (please describe):

## Checklist
- [x] Code updated to current develop branch head
- [x] Passes CI checks
- [x] Is a part of an issue
- [ ] Tests added for the bugfix or newly implemented feature, describe below why if not
- [ ] Changelog is updated
- [ ] Documentation of code and features exists

## Changes

- Refactor UI to show room type settings, replace interactive looking elements with static elements

## Screenshots of new design

<img width="934" alt="image" src="https://github.com/THM-Health/PILOS/assets/4281791/c54bc6c9-4965-42f5-930c-d991b658f818">

<img width="547" alt="image" src="https://github.com/THM-Health/PILOS/assets/4281791/4a3d6e87-357d-42c6-b8a6-482882f27254">

2024-06-17 16:43 UTC, SamuelWei commented
@tibroc What do you think?

2024-06-20 17:36 UTC, Sabr1n4W requested changes
Maybe also change "fas fa-times" to "fa-solid fa-xmark" in RoomTypeCompareSettingsField and in RoomTypeSettingsField

2024-06-20 17:36 UTC, Sabr1n4W commented on resources/js/components/RoomTypeDetails.vue
>              </div>
```suggestion
            <!-- Show all room settings grouped by category -->
            <div v-for="settingGroup in roomTypeSettings" :key="settingGroup.title">
              <h4 class="my-2">{{ settingGroup.title }}</h4>
              <RoomTypeSettingsField
                v-for="setting in settingGroup.settings"
                :key="setting.key"
                :id="setting.key"
                :value="roomType[setting.key+'_default']"
                :enforced="roomType[setting.key+'_enforced']"
                :label="setting.label"
                :roomType="roomType"
                :type="setting.type"
                :options="setting.options"
              />
            </div>
```

Maybe change setting to settingGroup or something similar and field to setting

2024-06-25 10:04 UTC, tibroc commented
Looks a lot better imo! :rocket:

2024-07-16 12:54 UTC, merged