Configurable hook script for recording synchronization
THM-Health/PILOS pull request #1604
Opened 2024-11-21 17:32 UTC by pizkaz

# Fixes #1484 

## Type (Highlight the corresponding type)

-   Bugfix
-   **Feature**
-   Documentation
-   Refactoring (e.g. Style updates, Test implementation, etc.)
-   Other (please describe):

## Checklist

-   [x] Code updated to current develop branch head
-   [ ] Passes CI checks
-   [x] Is a part of an issue
-   [ ] Tests added for the bugfix or newly implemented feature, describe below why if not
-   [ ] Changelog is updated
-   [x] Documentation of code and features exists

## Changes

- Introduces a new environment variable `RECORDING_IMPORT_BEFORE_HOOK` which can be set to a path to a script. If set, said script is called before importing new recordings from the spool directory. This can be handy in situations where one cannot configure BBB to "push" recordings to PILOS to implement a "pull" mechanism.
- `ImportRecordingsCommand` is now called `withoutOverlapping()`

## Other information

2024-11-22 16:13 UTC, SamuelWei requested changes
I added tests and updated the changelog

2024-11-22 16:13 UTC, SamuelWei commented on docs/docs/administration/08-advanced/02-recording.md
> +If you are unable to push recordings to your PILOS server as described above, you can call let PILOS call a hook script before importing recordings.
Wording 'you can call let PILOS call'

2024-11-22 16:15 UTC, SamuelWei commented on CHANGELOG.md
> +
Add the `withoutOverlapping` change to the `### Changed` section and explain what it does

2024-11-23 09:45 UTC, pizkaz commented on docs/docs/administration/08-advanced/02-recording.md
> +If you are unable to push recordings to your PILOS server as described above, you can call let PILOS call a hook script before importing recordings.
Fixed.

2024-11-23 09:45 UTC, pizkaz commented on CHANGELOG.md
> +
Done.

2024-11-25 07:56 UTC, SamuelWei approved these changes

2024-11-25 08:12 UTC, merged