WIP: Provisioning service
THM-Health/PILOS pull request #1678
Opened 2024-12-09 10:09 UTC by pizkaz

# Fixes \#

## Type (Highlight the corresponding type)

- **Bugfix**
- Feature
- Documentation
- Refactoring (e.g. Style updates, Test implementation, etc.)
- Other (please describe):

## Checklist

- [ ] Code updated to current develop branch head
- [ ] Passes CI checks
- [ ] Is a part of an issue
- [ ] Tests added for the bugfix or newly implemented feature, describe below why if not
- [ ] Changelog is updated
- [ ] Documentation of code and features exists

## Changes

-
-
-
-

## Other information

2024-12-19 10:26 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +        'servers' => 'required|list',
```suggestion
        'servers' => 'required|list|distinct|exists:servers,name',
```

2024-12-19 10:28 UTC, samuelwei commented on app/Services/ProvisioningService.php
> +        'server_pool' => 'required|string',
```suggestion
        'server_pool' => 'required|exists: server_pools,name',
```

2025-01-06 16:16 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +        'servers' => 'required|list',
Done with latest [rebase](https://github.com/THM-Health/PILOS/commit/a9067996faa947ab77008966c73bb8fe5cda7c33).

2025-01-06 16:16 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +        'server_pool' => 'required|string',
Done with latest [rebase](https://github.com/THM-Health/PILOS/commit/a9067996faa947ab77008966c73bb8fe5cda7c33).

2025-01-06 16:26 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +                $name = $item->name ?? "$item->firstname $item->lastname";
Some models already have a method `getLogLabel` https://github.com/THM-Health/PILOS/blob/develop/app/Models/User.php#L80
You could use this and add it to all models you need and that still don't have it

2025-01-06 16:27 UTC, samuelwei commented on app/Services/ProvisioningService.php
> +        $name = $properties->name ?? "$properties->firstname $properties->lastname";
This looks like it could we hard to maintain if more models without name are in need of this in the future. Maybe add a new function argument `string $label` and use this instead

2025-01-06 16:35 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +        $name = $properties->name ?? "$properties->firstname $properties->lastname";
That's exactly how it was at some point. :laughing: 
We can change it back as soon as it becomes necessary. For now, it's cleaner this way IMHO.
But if you insist, I can re-add the `string $name` argument right away.

2025-01-06 16:38 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +                $name = $item->name ?? "$item->firstname $item->lastname";
I like that. This would also solve the `$name` "problem" in `createWrapper`. Will do!

2025-01-06 17:55 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +        $name = $properties->name ?? "$properties->firstname $properties->lastname";
Solved with an overridable function in `AbstractProvisioner`.

2025-01-06 17:55 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +                $name = $item->name ?? "$item->firstname $item->lastname";
Done.

2025-01-07 07:56 UTC, SamuelWei requested changes

2025-01-07 07:56 UTC, SamuelWei commented on docs/docs/administration/08-advanced/05-provisioning.md
> +docker compose exec app pilos-cli provisioning_data.json
Please check this command, I doubt this works

2025-01-07 07:59 UTC, SamuelWei commented on app/Console/Commands/ProvisionCommand.php
> +        $this->provision->settings->set($data->settings);
(Optional) You could put this into a try catch and a Database transaction before and after, so the user can decide if an incomplete provision should be reverted

2025-01-07 08:11 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +        return ltrim($name);
```suggestion
        return Str::of($name)->snake()->replace("_", " ")->value();
```

2025-01-07 08:23 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +    protected function modelName()
This could be computed in the constructor and saved as a variable, instead of beeing computed multiple times.
Maybe make this and the variable private and change $model to a const

2025-01-07 08:57 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +        foreach ($items as $item) {
```suggestion
        $query = $this->model::query();
        foreach ($match as $key => $value) {
          $query = $query->where($key, $value);
        }
        
        $query->get()->each(function (object $item) {
```

2025-01-07 09:12 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +            $srv->status = constant($status)->value;
```suggestion
            try{
                $status = App\Enums\ServerStatus::{strtoupper($properties->status)};
            }
            catch (Error $e){
                throw new UnexpectedValueException('Invalid server status');
            }
            
            $srv->name = $properties->name;
            $srv->description = $properties->description;
            $srv->base_url = $properties->endpoint;
            $srv->secret = $properties->secret;
            $srv->strength = $properties->strength;
            $srv->status = $status;
```

2025-01-07 09:22 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +        'roles' => 'required|list|exists:roles,name',
add distinct

2025-01-07 09:24 UTC, samuelwei commented on app/Services/ProvisioningService.php
> +        'timezone' => 'required|string',
```suggestion
        'timezone' => ['required', 'string', Rule::in(timezone_identifiers_list())],
```

2025-01-07 09:24 UTC, samuelwei commented on app/Services/ProvisioningService.php
> +        'locale' => 'required|string',
```suggestion
        'locale' => ['required', 'string', Rule::in(array_keys(config('app.enabled_locales')))],
```

2025-01-07 09:26 UTC, samuelwei commented on app/Services/ProvisioningService.php
> +            }
Could this be obsolute due to the validation rule, that already checks that a role with this name exists.
See ServerPoolProvisioner where this additional check is missing

2025-01-07 09:31 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +        'servers.*' => 'string',
```suggestion
        'servers' => 'required|list',
        'servers.*' => 'string|distinct|exists:servers,name',
```
I'm unsure of the other syntax also works. Thats at least how we usually check it

2025-01-07 09:33 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +        'roles.*' => 'string',
```suggestion
        'roles' => 'required|list',
        'roles.*' => 'string|distinct|exists:roles,name',
```
See my comment in ServerPoolProvisioner

2025-01-07 09:42 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +    public static array $expectedProperties = [
This is far less strict than app/Http/Requests/UpdateSettings.php, unsure if this can cause trouble if values are set out of the desired range

2025-01-07 10:23 UTC, pizkaz commented on docs/docs/administration/08-advanced/05-provisioning.md
> +docker compose exec app pilos-cli provisioning_data.json
Indeed.

2025-01-07 10:35 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +        return ltrim($name);
Laravel is awesome.

2025-01-07 11:28 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +    protected function modelName()
I can't wrap my head around PHP's concept of constants but I'm using constructors and private vars to configure concrete provisioners now.

2025-01-07 11:33 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +        foreach ($items as $item) {
Done.

2025-01-07 11:42 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +            $srv->status = constant($status)->value;
Thanks, I couldn't get this to work. :pray: 
`try / catch` is unnecessary because of input validations.

2025-01-07 11:45 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +            }
Indeed.

2025-01-07 11:57 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +        'servers.*' => 'string',
`exists:...` works, `distinct` does not. In any case adding both constraints to the individual items is clearer.

2025-01-07 12:03 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +        'roles.*' => 'string',
Fixed.

2025-01-07 14:27 UTC, pizkaz commented on app/Console/Commands/ProvisionCommand.php
> +        $this->provision->settings->set($data->settings);
Good idea! Done.

2025-01-07 14:33 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +        'timezone' => 'required|string',
Done.

2025-01-07 14:36 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +        'locale' => 'required|string',
Done.

2025-01-07 14:39 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +    public static array $expectedProperties = [
We should try to avoid inconsistencies. I'll try to recycle those rules as copying them (=> duplicating code) feels wrong.

2025-01-07 23:26 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +    public static array $expectedProperties = [
Done. Also found bugs in test data :face_with_peeking_eye:.

2025-01-11 14:23 UTC, pizkaz commented
Just tested this in a k8s environment: Works like a charm. \o/

2025-01-14 11:16 UTC, SamuelWei requested changes

2025-01-14 11:16 UTC, SamuelWei commented on app/Services/ProvisioningService.php
> +            'color' => 'required|string',
```suggestion
            'color' => 'required|string|hex_color',
```

2025-01-14 11:16 UTC, SamuelWei commented on docs/docs/administration/08-advanced/05-provisioning.md
> +docker compose exec app pilos-cli provision:all provisioning_data.json
The file path must be inside the container! Eg, place it into a mounted folder or copy file into container and delete afterwards

2025-01-14 11:16 UTC, SamuelWei commented on docs/docs/administration/08-advanced/05-provisioning.md
> +| `color`       | `string` | Color used for the room type in frontend    |
Hex-Color used for the room type...

2025-01-14 11:16 UTC, samuelwei commented on docs/docs/administration/08-advanced/05-provisioning.md
> +| `locale`        | `string`   | One of [`de`, `de-gender`, `en`, `fr`] |
One of the locales enabled in `ENABLED_LOCALES` (env) or if this is not set, one of the locales stored in the `lang` directory (similar to https://thm-health.github.io/PILOS/docs/next/administration/configuration#user-interface-and-localization-configuration)

2025-01-14 12:48 UTC, pizkaz commented on app/Services/ProvisioningService.php
> +            'color' => 'required|string',
Done.

2025-01-14 13:02 UTC, pizkaz commented on docs/docs/administration/08-advanced/05-provisioning.md
> +docker compose exec app pilos-cli provision:all provisioning_data.json
Done.

2025-01-14 13:02 UTC, pizkaz commented on docs/docs/administration/08-advanced/05-provisioning.md
> +| `locale`        | `string`   | One of [`de`, `de-gender`, `en`, `fr`] |
Done.

2025-01-14 13:03 UTC, pizkaz commented on docs/docs/administration/08-advanced/05-provisioning.md
> +| `color`       | `string` | Color used for the room type in frontend    |
Done.

2025-01-14 15:21 UTC, merged