Transfer room ownership
THM-Health/PILOS pull request #686
Opened 2023-11-13 14:36 UTC by Sabr1n4W

# Fixes \#532

## Type (Highlight the corresponding type)
- Bugfix
- **Feature**
- Documentation
- Refactoring (e.g. Style updates, Test implementation, etc.)
- Other (please describe):

## Checklist
- [ ] Code updated to current develop branch head
- [ ] Passes CI checks
- [x] Is a part of an issue
- [ ] Tests added for the bugfix or newly implemented feature, describe below why if not
- [ ] Changelog is updated
- [ ] Documentation of code and features exists

## Changes

- transfer room ownership

2023-12-21 21:20 UTC, SamuelWei requested changes

2023-12-21 21:20 UTC, SamuelWei commented on resources/js/components/Room/TransferOwnershipDropdownButton.vue
> +      if ((this.stayInRoom && this.newRoleInRoom == null) || this.fieldState('role') === false) { return false; }
This is always true, thus can be remove here and from data

2023-12-22 11:33 UTC, Sabr1n4W commented on tests/Frontend/views/rooms/View.spec.js
I think we decided to add this here #721

2024-01-09 08:38 UTC, SamuelWei approved these changes

2024-01-09 09:12 UTC, merged