Add server pooling
THM-Health/PILOS pull request #99
Opened 2021-01-12 19:38 UTC by SamuelWei

# Fixes #96 

## Type (Highlight the corresponding type)
- Bugfix
- **Feature**
- Documentation
- Refactoring (e.g. Style updates, Test implementation, etc.)
- Other (please describe):

## Checklist
- [x] Code updated to current masters head
- [x] Passes CI checks
- [x] Is a part of an issue
- [ ] Tests added for the bugfix or newly implemented feature, describe below why if not
- [ ] Changelog is updated
- [ ] Documentation of code and features exists

## Changes

- Added server pools
- Added attribute name to servers
- Added server pools to room types
- Changed load balancer to only use servers from the server pool of the room's room type
- Adjusted tests

## Other information

2021-02-03 19:46 UTC, dennis95stumm requested changes

2021-02-03 19:46 UTC, dennis95stumm commented on resources/js/views/settings/serverPools/Index.vue
> +        { key: 'server_count', label: this.$t('settings.serverPools.serverCount'), sortable: true }
The sorting does not work since this field is not whitelisted in the controller method!

2021-02-03 19:46 UTC, dennis95stumm commented on resources/js/views/settings/serverPools/View.vue
> +                      <span @click='remove(option)'><b-icon-x :aria-label="$t('settings.servers.removeServer')"></b-icon-x></span>
The locale does not exist!

2021-02-03 19:46 UTC, dennis95stumm commented on resources/js/views/settings/serverPools/View.vue
> +      modelLoadPromise: Promise.resolve(),
The property is never set and useless!

2021-02-03 19:46 UTC, dennis95stumm commented on tests/Feature/api/v1/ServerPoolTest.php
> +    }
Add test with sorting by server_count

2021-02-04 09:00 UTC, SamuelWei commented on database/migrations/2021_01_12_135520_add_name_to_servers.php
> +            $table->renameColumn('description', 'name');
Because I wanted to make name a non-nullable attribute, so I rename description to name and create a new nullable field description

2021-02-04 11:41 UTC, SamuelWei commented on database/migrations/2021_01_12_151029_add_server_pool_to_room_types.php
> +            $table->unsignedBigInteger('server_pool_id')->default(\App\ServerPool::all()->first()->id);
I now create the foreignKey as nullable, link all exisiting room types to the seeders default server pool and make the foreignKey non-nullable.

2021-02-04 17:57 UTC, dennis95stumm approved these changes

2021-02-04 17:57 UTC, merged